### ISSUE TITLE
Update version for new SDK?

### ISSUE THREAD

**Issue by frekel** [jordenc/com.lg.hombot#3]
Hi,

Any change you will update your app to the new SDK version?

Greets,
Frank

**Comment by jordenc** [comment]
I hope to start on this shortly, which means within a couple of weeks. Sorry for the delays, it has been on my todolist for a long time but I'm very busy with work currently.

**Comment by frekel** [comment]
Hi,

I took the liberty to rewrite the app into a SDK3 version. Can you contact me so we can discuss how to proceed?
https://github.com/frekel/nl.vanderstad.hombot

Greets,
Frank

**Comment by jordenc** [comment]
That's amazing! Looking forward to test it. The URL doesn't seem to work though.

Feel free to contact me (can be in Dutch ;-)) on info [at] corbata.nl

**Comment by frekel** [comment]
@jordenc You should have access to the repo now and a :mailbox:  is sent ;)

Will close this issue for now as we have direct contact!
